# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Lyles' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Lyles

  target 'LylesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'PubCore' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PubCore

  target 'PubCoreTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
